name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2022
    steps:

      # region JOM

      - name: JOM Cache Restore
        id: jom-cache
        uses: actions/cache/restore@v4.2.0
        with: 
          key: jom
          path: |-
            C:\jom\jom.zip

      - name: JOM Download
        if: steps.jom-cache.outputs.cache-hit != 'true'
        run: |-
          md C:\jom
          curl.exe -fsSL http://download.qt.io/official_releases/jom/jom.zip -o C:\jom\jom.zip

      - name: JOM Cache Save
        if: steps.jom-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4.2.0
        with: 
          key: jom
          path: |-
            C:\jom\jom.zip

      - name: JOM extract
        run: Expand-Archive C:\jom\jom.zip -DestinationPath C:\jom

      - name: Add JOM to PATH
        uses: actions/github-script@v7.0.1
        with:
          script: |-
            core.addPath('C:\\jom');

      - name: test jom (pwsh)
        run: gcm jom

      # endregion

      # region winflexbison

      - name: winflexbison Cache Restore
        id: winflexbison-cache
        uses: actions/cache/restore@v4.2.0
        with: 
          key: winflexbison
          path: |-
            C:\winflexbison\winflexbison.zip

      - name: winflexbison Download
        if: steps.winflexbison-cache.outputs.cache-hit != 'true'
        run: |-
          md C:\winflexbison
          curl.exe -fsSL https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip -o C:\winflexbison\winflexbison.zip

      - name: winflexbison Cache Save
        if: steps.winflexbison-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4.2.0
        with: 
          key: winflexbison
          path: |-
            C:\winflexbison\winflexbison.zip

      - name: winflexbison extract
        run: Expand-Archive C:\winflexbison\winflexbison.zip -DestinationPath C:\winflexbison

      - name: debug winflexbison
        run: ls c:\winflexbison

      # endregion

      - name: Setup WSL2
        uses: vedantmgoyal9/setup-wsl2@v1.1.0

      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.5.1

      - name: disable autocrlf
        run: git config --global core.autocrlf input

      - name: test jom (wsl)
        run:
          wsl which jom.exe

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        shell: pwsh
        run: |-

          Set-PSDebug -Trace 2

          wsl sudo ln -s /usr/bin/python3 /usr/bin/python

          wsl sudo

          wsl bash -exv ./buildall.sh 1 9 R
